In [39]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.linear_model import LogisticRegression

In [2]:
df=pd.read_csv('/content/diabetes.csv')

In [4]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [6]:
df.shape

(768, 9)

In [5]:
df.info

<bound method DataFrame.info of      Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   5

In [14]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [21]:
df.describe().round(2)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin     BMI  \
count       768.00   768.00         768.00         768.00   768.00  768.00   
mean          3.85   120.89          69.11          20.54    79.80   31.99   
std           3.37    31.97          19.36          15.95   115.24    7.88   
min           0.00     0.00           0.00           0.00     0.00    0.00   
25%           1.00    99.00          62.00           0.00     0.00   27.30   
50%           3.00   117.00          72.00          23.00    30.50   32.00   
75%           6.00   140.25          80.00          32.00   127.25   36.60   
max          17.00   199.00         122.00          99.00   846.00   67.10   

       DiabetesPedigreeFunction     Age  Outcome  
count                    768.00  768.00   768.00  
mean                       0.47   33.24     0.35  
std                        0.33   11.76     0.48  
min                        0.08   21.00     0.00  
25%                        0.24   24.00     0.00  
50%                        0.37   29.00     0.00  
75%                        0.63   41.00     1.00  
max                        2.42   81.00     1.00

In [197]:
X=df.drop(columns='Outcome', axis=1)
y=df['Outcome']

In [249]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [250]:
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [251]:
X_train_scaled=pd.DataFrame(X_train_scaled, columns=X_train.columns)
X_test_scaled=pd.DataFrame(X_test_scaled, columns=X_test.columns)


In [252]:
X_train_scaled

Pregnancies   Glucose  BloodPressure  SkinThickness   Insulin       BMI  \
0      -0.526397 -1.151398      -3.752683      -1.322774 -0.701206 -4.135256   
1       1.588046 -0.276643       0.680345       0.233505 -0.701206 -0.489169   
2      -0.828460  0.566871      -1.265862      -0.090720  0.013448 -0.424522   
3      -1.130523  1.254179      -1.049617      -1.322774 -0.701206 -1.303720   
4       0.681856  0.410665       0.572222       1.076490  2.484601  1.838121   
..           ...       ...            ...            ...       ...       ...   
609     0.379793  0.566871      -0.292759       0.946800  0.504235 -0.437451   
610    -0.828460 -0.776503       2.842797      -1.322774 -0.701206 -1.239073   
611     1.890109 -0.620297       0.896590       1.076490 -0.701206  1.760544   
612    -1.130523  0.629354      -3.752683      -1.322774 -0.701206  1.346804   
613    -1.130523  0.129493       1.437203      -1.322774 -0.701206 -1.226144   

     DiabetesPedigreeFunction       Age  
0                   -0.490735 -1.035940  
1                    2.415030  1.487101  
2                    0.549161 -0.948939  
3                   -0.639291  2.792122  
4                   -0.686829  1.139095  
..                        ...       ...  
609                 -0.172824 -0.600933  
610                 -0.778934 -0.513932  
611                  1.981245  0.443084  
612                 -0.784877 -0.339929  
613                 -0.615522 -1.035940  

[614 rows x 8 columns]

#Model 1
#Logistic Regression


In [253]:
lr = LogisticRegression()
lr.fit(X_train_scaled, y_train)


LogisticRegression()

In [254]:
y_test_predr=lr.predict(X_test_scaled)

In [255]:
accuracy_test_lr=accuracy_score(y_test, y_test_pred)
print(f"Accuracy score for Logistic Regression model for test data set is:", accuracy_test_lr)

Accuracy score for Logistic Regression model for test data set is: 0.7532467532467533


In [256]:
y_train_pred=lr.predict(X_train_scaled)

In [257]:
accuracy_train_lr=accuracy_score(y_train, y_train_pred)
print(f"Accuracy score for Logistic Regression model for training data set is:", accuracy_train_lr)

Accuracy score for Logistic Regression model for training data set is: 0.7703583061889251


In [258]:
from sklearn.metrics import confusion_matrix

In [259]:
print(confusion_matrix(y_test, y_test_pred))

[[79 20]
 [18 37]]


#Model 2
#Random Forest Classifier

In [260]:
from sklearn.ensemble import RandomForestClassifier
rf= RandomForestClassifier(n_estimators=15, random_state=42)


In [261]:
rf.fit(X_train_scaled, y_train)

RandomForestClassifier(n_estimators=15, random_state=42)

In [262]:
y_pred_rf=rf.predict(X_test_scaled)

In [263]:
accuracy_test_rf=accuracy_score(y_test, y_pred_rf)
print(f"Accuracy score for Random Forest Classifier model is:", accuracy_test_rf)

Accuracy score for Random Forest Classifier model is: 0.7532467532467533


In [264]:
print(confusion_matrix(y_test, y_pred_rf))

[[78 21]
 [17 38]]


#Model 3
#SVM

In [265]:
from sklearn.svm import SVC

In [266]:
svm = SVC(kernel='linear', random_state=42)


In [267]:
svm.fit(X_train, y_train)

SVC(kernel='linear', random_state=42)

In [270]:
y_pred_svm=svm.predict(X_test)

In [271]:
accuracy_svm=accuracy_score(y_test, y_pred_svm)
print(f"Accuracy score for SVM model is:", accuracy_svm)

Accuracy score for SVM model is: 0.7532467532467533


In [272]:
print(confusion_matrix(y_test, y_pred_svm))

[[80 19]
 [19 36]]


#Making a predicitve system

In [277]:
input_data = (5,166,72,19,175,25.8,0.587,51)

# changing the input_data to numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

# standardize the input data
std_data = scaler.transform(input_data_reshaped)
print(std_data)

prediction = svm.predict(std_data)
print(prediction)

if (prediction[0] == 0):
  print('The person is not diabetic')
else:
  print('The person is diabetic')

[[ 0.37979288  1.41038486  0.13973176 -0.09071957  0.80559475 -0.79947408
   0.35009487  1.57410227]]
[0]
The person is not diabetic


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
